=== Arhor/epam_Task_4/Medicins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/Medicins" xmlns:tns="http://www.example.com/Medicins">
    
    <!-- TRANSLATE TO NORMAL ENGLISH -->
    
    <!-- XML document structure -->
    <element name="Medicins">
        <complexType>
            <sequence>
                <element ref="tns:Medicine" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <!-- substitution defenition -->
    <element name="Medicine"   type="tns:MedicineType"   abstract="true"/>
    <element name="Antibiotik" type="tns:AntibiotikType" substitutionGroup="tns:Medicine"/>
    <element name="Vitamin"    type="tns:VitaminType"    substitutionGroup="tns:Medicine"/>
    <element name="Painkiller" type="tns:PainkillerType" substitutionGroup="tns:Medicine"/>

    <!-- type defenition for abstract Medecine element -->
    <complexType name="MedicineType">
        <attribute name="Name" type="ID" use="required"/>
        <sequence>
            <element name="Pharm"   type="string"/>
            <element name="Analog"  type="string" use="optional"/>
            <element name="Version" type="tns:VersionType" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- type defenition for Antibiotik element -->
    <complexType name="AntibiotikType">
        <complexContent>
            <extention base="tns:MedicineType">
                <sequence>
                    <element name="Recipie" type="boolean" default="true"/>
                </sequence>
            </extention>
        </complexContent>
    </complexType>

    <!-- type defenition for Vitamin element -->
    <complexType name="VitaminType"></complexType>

    <!-- type defenition for Painkiller element -->
    <complexType name="PainkillerType"></complexType>

    <!-- type defenition for Version element -->
    <complexType name="VersionType">
        <attribute name="form" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="tabs"  />
                    <enumeration value="pills" />
                    <enumeration value="powder"/>
                    <enumeration value="liquid"/>
                </restriction>
            </simpleType>
        </attribute>
        <sequence>
            <element name="Certificate" type="tns:CertificateType"/>
            <element name="Package"     type="tns:PackageType"/>
            <element name="Dosage"      type="tns:DosageType"/>
        </sequence>
    </complexType>

    <!-- type defenition for Certificate element -->
    <complexType name="CertificateType">
        <attribute name="RegistrationID" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="(\\d){3}-([A-Za-z0-9]){5}"/>
                </restriction>
            </simpleType>
        </attribute>
        <sequence>
            <element name="RegistredBy"      type="string"/>
            <element name="RegistrationDate" type="date"/>
            <element name="ExpireDate"       type="date"/>
        </sequence>
    </complexType>

    <!-- type defenition for Package element -->
    <complexType name="PackageType">
        <attribute name="size">
            <simpleType>
                <restriction base="string">
                    <enumeration value="small"></enumeration>
                    <enumeration value="medium"></enumeration>
                    <enumeration value="large"></enumeration>
                </restriction>
            </simpleType>
        </element>
        <element name="Amount" type="positiveInteger"/>
        <element name="Price"  type="double"/>
    </complexType>

    <!-- type defenition for Dosage element -->
    <complexType name="DosageType">
        <element name="Amount"    type="string"/>
        <element name="Frequency" type="positiveInteger"/>
    </complexType>
</schema>

=== Arhor/epam_Task_4/Medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Medicins xmlns:tns="http://www.example.com/Medicins"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.com/Medicins Medicins.xsd">

    <Antibiotik name="Betadine">
    	<Pharm>Legacy inc.</Pharm>
    	<Analog>Striptodine</Analog>
    	<Version form="tabs">
    		<Certificate registrationID="123-9AA57">
    			<RegistredBy>World Healthprotection Federation</RegistredBy>
    			<RegistrationDate>13-07-2009</RegistrationDate>
    			<ExpireDate>12-07-2019</ExpireDate>
    		</Certificate>
    		<Package size="small">
    			<Amount>30</Amount>
    			<Price>19.99</Price>
    		</Package>
    		<Package size="medium">
    			<Amount>60</Amount>
    			<Price>35.99</Price>
    		</Package>
    		<Package size="large">
    			<Amount>90</Amount>
    			<Price>61.99</Price>
    		</Package>
    		<Dosage>
    			<Amount>15 mg.</Amount>
    			<Frequency>3</Frequency>
    		</Dosage>
    	</Version>
    </Antibiotik>

</tns:Medicins>
